##########################################################
##########################################################
### FUNCTIONS USED BY THE NBS POTENTIALS SCENARIO WORK ###
##########################################################

#####################################################################
### Function to calculate proportional adoption of an NBS pathway ###
#####################################################################

### INPUTS:

## timeframe_df: dataframe format - requires the column 'year':
  # 'year' - An integer vector that states the years that proportional adoptiong should be calculated for (e.g. 2000 - 2100)
## year_start: An integer stating in which year the NBS pathway reaches 0.1% gross enrollment of maximal extent (i.e. if the maximum extent is 1,000,000 ha, then the year in which 1,000 ha has been enrolled) (e.g. 2025)
## year_50: An integer stating in which year the NBS pathway reaches 50% gross enrollment of maximal extent (i.e. if the maximum extent is 1,000,000 ha, then the year in which 500,000 ha has been enrolled) (e.g. 2060)
## saturation: The number of years that the NBS pathway is deemed to continually generate emission reductions (e.g. once 'enrolled' a reforestation hectare is expected to generate additional ERs for 30 years before that hectare is unenrolled)

### OUTPUTS:

## Dataframe format with multiple columns that correspond to the years timeframe column that was input:
  # 'enrol' - A numeric vector that states the absolute cumulative area that has been enrolled, expressed as a proportion of given extent (i.e. 0-1)
  # 'unenrol' - A numeric vector that states the absolute cumulative area that has been unenrolled, expressed as a proportion of given extent (i.e. 0-1)
  # 'net_enrol' - A numeric vector that states the difference between the area enrolled in year X minus the area unenrolled in year X, expressed as a proportion of given extent (i.e. 0-1 though it will never be close to 0 or 1)
  # 'diff_enrol' - A numeric vector that states the annual change in gross enrollment from year to year, expressed as a proportion of given extent (i.e. 0-1) (e.g. if this is 0.1 in a year, then 10% of the available extent was enrolled that year)
  # 'diff_unenrol' - A numeric vector that states the annual change in gross unenrollment from year to year, expressed as a proportion of given extent (i.e. 0-1) (e.g. if this is 0.1 in a year, then 10% of the available extent was unenrolled that year, regardless of how much was enrolled)
  # 'diff_net' - A numeric vector that states the annual change in net enrollment from year to year, expressed as a proportion of given extent (i.e. 0-1) (e.g. if this is 0.1 in a year, then the difference between enrollment and unenrollment in that year was 10% of the available extent - i.e. it could be that 15% was enrolled but 5% was unenrolled)

proportional_adoption = function(timeframe_df, year_start, year_50, saturation) {
  enrol = 1/(1+exp(-((log(1/0.001-1)-log(1/0.5-1))/(year_50-year_start))*(timeframe_df$year-(log(1/0.001-1)/((log(1/0.001-1)-log(1/0.5-1))/(year_50-year_start))+year_start)))) # Calculate enrollment of each NBS
  unenrol = 1/(1+exp(-((log(1/0.001-1)-log(1/0.5-1))/(year_50-year_start))*((timeframe_df$year-saturation)-(log(1/0.001-1)/((log(1/0.001-1)-log(1/0.5-1))/(year_50-year_start))+year_start)))) # Calculate unenrollment of each NBS
  net_enrol = enrol - unenrol # Calculate the net change
  diff_enrol = c(0,diff(enrol)) # Calculate annual enrollment difference over time
  diff_unenrol = c(0,diff(unenrol)) # Calculate annual unenrollment difference over time
  diff_net = c(0,diff(net_enrol)) # Calculate annual net enrollment difference when accounting for unenrollment
  return(cbind(timeframe_df, enrol, unenrol, net_enrol, diff_enrol, diff_unenrol, diff_net)) # Output the resulting dataframe
} # End of function


##################################################################################################################
### Function to calculate 'staggered' Emission Reductions based on temporal profiles of the different pathways ###
##################################################################################################################

### INPUTS:

## area_timeframe_data: dataframe format - requires the columns 'year' and 'diff_net':
  # 'year' - An integer vector that states the years that emission reductions should be calculated for (e.g. 2000 - 2100)
  # 'area_Mha' - A numeric vector that states the annual net area enrolled (i.e. diff_net output from proportional_adoption function) to generate emission reductions for the aforementioned years (in hectares or equivalent)
## saturation: integer vector that states the number of years that a hectare is enrolled before being unenrolled - equates to 'number of years that emission reductions are generated by that hectare'
## function_type: categorical character vector type with 3 factor levels (linear, constant, pulse) refers to temporal profile in annual emission reductions for that NBS type. Details on options below:
  # linear = linear ramp up from 0 tCO2/ha/yr in year 0 to maximum tCO2/ha/yr in 'years_to_max' (see additional input parameter below) and then sustained for the remaining portion of the 'saturation timeline' (as defined by 'saturation' parameter above)
  # constant = given annual ER intensity (tCO2/ha/yr; ter_intensity parameter below) is generated every year during entire 'saturation timeline'
  # pulse = all emission reductions are generated immediately in year 1 but land must be protected for saturation timeline with 0 emissions generated each year after year 1 (note - should align with a complimentary ter_intensity designation)
## years_to_max: integer vector that states the number of years before the maximum emission reduction intensity is reached (used when function_type is linear, as described above)
## ter_intensity: numeric vector of annual emission reduction intensity (i.e. tCO2/ha/yr) of an NBS type that is used to convert the area (Ha) into total emission reductions (TERs)
## force_average: boolean vector to determine whether the total proportion should average to 1 or not (i.e. if proportional ER intensity is ramped up over 10 years then the final average will be < 1, which translates to fewer emission reductions over time.
  # Setting this to TRUE (the default) forces the remaining years (after the ramp up) to compensate for this and increase remaining ERs/year)

### OUTPUTS:

## Dataframe format equivalent to 'area_timeframe_data' with one additional column called 'TERs_MtCO2'
  # 'TERs_MtCO2' - A numeric vector that states the absolute emission reductions (tCO2e) generated by all active areas (i.e. excluding unenrolled area) for each year specified (e.g. 2000 - 2100)

annual_TER_calculator = function(area_timeframe_data, saturation, function_type, years_to_max, ter_intensity, force_average = T) {# annual_ER_intensity) {
  tmp = data.frame(time = 1:saturation) # Create simple dataframe of timeline from 1 to end of 'saturation horizon'
  if(function_type == "linear") { # Linear refers to a phased increase in emission reductions per hectare over time after enrollment
    if(force_average) {
      tmp$prop_annERs = ifelse((tmp$time/years_to_max)>1, 1+(((years_to_max+1)/2)-1)/(saturation-years_to_max), tmp$time/years_to_max)
    } else {
      tmp$prop_annERs = ifelse((tmp$time/years_to_max)>1, 1, tmp$time/years_to_max) # Linear regression to increase ERs up to maximum after X years, after max is reached it is sustained until unenrollment. NOTE - Could be a logistic function instead (e.g. (1/(1+exp(-0.4*annualERs$time))^5)) but need to link coefficients to 'years_to_max'
    }
  } else {
    if(function_type == "constant") { # Constant refers to a static number of emission reductions per hectare over time after enrollment
      tmp$prop_annERs = 1 # Fixed at 1 as a proportion of maximum annual ERs
    } else {
      if(function_type == "pulse") { # Avoid refers to those pathways where emission reductions are generated in the year they are avoided but not again afterwards
        tmp$prop_annERs = c(1, rep(0, length(tmp$time)-1)) # Proportion starts at 1 but is set to 0 for every year after that. Assumption is that area needs to remain protected.
      } else {
        cat("The 'function_type' that was input is not recognized. Current support for 'linear, constant or avoid only.") # In case there is an error thrown, print a message to console
      } # End of error statement
    } # End of avoid calculation 
  } # End of all if statements
  tmp$annualERs_tCO2_ha = tmp$prop_annERs*ter_intensity # Convert proportion to total using intensity
  annual_ERs = area_timeframe_data # Create replicated dataframe to put calculated data into
  annual_ERs$TERs_MtCO2 = NA # Empty column to fill
  for(yr in area_timeframe_data$year) { # Loop over all years in time range
    TERs = 0 # Reset TERs object to 0
    for(i in tmp$time) { # Loop over years of annual ERs temporal profile
      if(yr+1-i>=min(area_timeframe_data$year)) { # Needed to stop trying to calculate a year below the minimum of the time range (e.g. 2000)
        TERs = TERs + area_timeframe_data$area_Mha[area_timeframe_data$year==(yr+1-i)]*tmp$annualERs_tCO2_ha[tmp$time==i] # Cumulate emission reductions for that year (new area plus previously enrolled areas)
      } # End of if statement
    } # End of annual ER calculation loop
    annual_ERs$TERs_MtCO2[annual_ERs$year==yr] = TERs # Allocate the cumulated TERs to the created dataframe
  } # End of full time-frame loop
  return(annual_ERs) # Output the resulting calculation
} # End of function

